### ISSUE TITLE
Amazon S3

### ISSUE THREAD

**Issue by mattiasbergstrom** [bemtv/bemtv#43]
Any special settings needed to run from S3 ?

**Comment by flavioribeiro** [comment]
hi @mattiasbergstrom, serving the js components can be made using S3, but you'll need to have a tracker running on a dedicated server.

**Comment by mattiasbergstrom** [comment]
Hi

That was a quick answer :)

im having a problem collection the .m3u8 file from S3, works i VLC,
as i dont get the m3u8 i of course dont get the .ts files :)

just did a

source: "http://mpeg2trpsegments.s3.amazonaws.com/test.m3u8",

do you need a more "complete" .m3u8 file ?

**Comment by flavioribeiro** [comment]
oh, I think that BemTV expects a master-playlist instead of this one. Try adding this file:

```text
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=500000
test.m3u8
```

Save it as playlist.m3u8 and put http://mpeg2trpsegments.s3.amazonaws.com/playlist.m3u8 instead of test.m3u8 on the player. Tell me if it works for you.

**Comment by arpu** [comment]
hello

where can i found the tracker sourcecode ? 
best regards

**Comment by flavioribeiro** [comment]
Hey,

here: https://github.com/rtc-io/rtc-switchboard

There's also this (https://github.com/cfreeman/signalbox) one which
promises to implement the same protocol, but didn't test yet.

*Flávio Ribeiro *
*(flv.io <http://flv.io> | blog <http://flavioribeiro.com>)*
